spring:
  application:
    name: ironman
  profiles:
    active: switch-develop
  cloud:
    bus:
      destination: jaehun-platform.prod.event.config-event.json
  config:
    import: optional:configserver:http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh