spring:
  application:
    name: ironman
  profiles:
    active: switch-develop
  config:
    import: optional:configserver:http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: refresh