spring:
  application:
    name: ratelimiter
  profiles:
    active: switch-develop
  cloud:
    bus:
      destination: jaehun-platform.prod.event.config-event.json
  config:
    import: optional:configserver:http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
    instances:
      transfer-limit:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
      banks:
        limitForPeriod: 7
        limitRefreshPeriod: 10s
        timeoutDuration: 1s