spring:
  application:
    name: veronica
  cloud:
    config:
      server:
        git:
          uri: https://github.com/biggwang/spring-config-repo
          clone-on-start: true
          search-paths: ironman/**
          default-label: main
#  security:
#    user:
#      name: root
#      password: s3cr3t
