spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Password
    hikari:
      maximum-pool-size: 10 # default 10
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#logging:
#  level:
#    org.hibernate.type.descriptor.sql: trace