name: Delete abandoned branches

on:
  # Run daily at midnight
  schedule:
    - cron: "0/1 * * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Satisfy my repo CDO
    steps:
      - name: Delete abandoned branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v2.0.3
        id: delete_stuff
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 1
          allowed_prefixes: release/
          ignore_branches: master,main,sandbox,develop

          # Disable dry run and actually get stuff deleted
          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"
