name: Delete branches

on: "push"

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Satisfy my repo CDO
    steps:
    - name: Delete pr-* branches
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{github.token}}
        branches: "*"
        prefix: feature-