name: delete branch on close pr
on: 
  pull_request:
    types: [closed]
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        exclude: 
          - development
          - qa
          - feature-*
        delete_closed_pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}